navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 0.0
    magnetic_declination_radians: 0.0  # Update this based on Udupi/Poland!
    yaw_offset: 0.0                    # Assuming IMU reads 0 when facing East. Adjust if needed.
    zero_altitude: true
    broadcast_cartesian_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
