rtabmap:
  ros__parameters:
    # Core
    subscribe_rgbd: True
    frame_id: "base_link"
    map_frame_id: 'map'
    odom_frame_id: "odom"
    publish_tf: True
    visual_odometry: False 
    subscribe_depth: True
    subscribe_rgb: True
    subscribe_rgbd: False
    approx_sync: True
    subscribe_odom: True
    wait_for_transform: 2.0

    # Grid Map Generation
    Grid/CellSize: "0.05"
    Grid/RangeMax: "5.0"
    Grid/RangeMin: "0.3"

    Grid/MinClusterSize: "5"
    Grid/ClusterRadius: "0.1"

    Grid/RayTracing: "true"
    # Grid/MaxGroundAmgle: "45"
    Grid/NormalSegmentation: "true"
    # Grid/NormalK: "20"

    Grid/MinMapSize: "1000"

    Grid/MinObstacleHeight: "0.05"
    Grid/MaxObstacleHeight: "1.5"

    'Grid/MaxObstacleHeight':    '2.0'   # ignore anything above this (m)

    # --- Optional but useful with segmentation ---
    Grid/3D:                   'false'   # use 3D grid (needed for segmentation)
    Grid/FlatObstacleDetected: 'true'   # detect flat obstacles (e.g. curbs)
    Grid/MaxGroundAngle:        "30.0"   # max angle for ground (degrees)

    # Grid/NoiseFilteringRadius: 0.05
    # Grid/NoiseFilteringMinNeighbors: 8                